### ISSUE TITLE
I moved some MCscripts files

### ISSUE THREAD

**Issue by TapeWerm** [nanabach-darkserver/integrated-mcbeserv-system#2]
MCscripts has a new directory named `/opt/MCscripts`. I moved Bash script SH files, the `backup_dir` symlink, and the `.mcbe_log` directory to there. I did this because `/opt/MCscripts` is owned by root and read only for the mc user. It's good security practice to limit the mc user's permissions on script files root executes and config files for those scripts. If you have any questions let me know. Sorry for the inconvenience.

https://github.com/TapeWerm/MCscripts/compare/118e191...8460724 shows the user facing changes.

**Comment by nanabach71** [comment]
Thanks for letting me know!
I'll deal with changes.

**Comment by nanabach71** [comment]
I checked changes and find that good install scripts are added. They worked successfully on my server.
I think using them is better than using playbook in this repository.
So I removed playbooks for installing. ea40e6cdd2391a32a775037b1f62daabdf78c03e
